/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseModal: typeof import('./components/atoms/BaseModal.vue')['default']
    CreateUsers: typeof import('./components/CreateUsers.vue')['default']
    FormLogin: typeof import('./components/FormLogin.vue')['default']
    ListUsers: typeof import('./components/ListUsers.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
